return {
  pic =love.graphics.newImage('assets/pics/player.png'),
  cellsizex = 16,
  cellsizey = 24,
  nbcellx = 20,
  nbcelly = 1,
  cellnames = {
    'down1',
    'down2',
    'down3',
    'up1',
    'up2',
    'up3',
    'right1',
    'right2',
    'right3',
    'left1',
    'left2',
    'left3',
    'hurtdown',
    'hurtup',
    'hurtright',
    'hurtleft',
    'hitdown',
    'hitup',
    'hitright',
    'hitleft',
  }
}
