asm:add(asset:newSpritesheet(require('assets/spritesheets/player')),'player')
asm:add(asset:newSpritesheet(require('assets/spritesheets/skeleton')),'skeleton')
asm:add(asset:newSpritesheet(require('assets/spritesheets/graveyard')),'graveyard')
asm:add(asset:newSpritesheet(require('assets/spritesheets/whip')),'whip')
asm:add(asset:newSpritesheet(require('assets/spritesheets/title')),'title')
asm:add(asset:newSpritesheet(require('assets/spritesheets/gameover')),'gameover')
