asm:add(asset:newSpritesheet(require('assets/spritesheets/s_player')),'player')
asm:add(asset:newSpritesheet(require('assets/spritesheets/s_skeleton')),'skeleton')
asm:add(asset:newSpritesheet(require('assets/spritesheets/s_graveyard')),'graveyard')
asm:add(asset:newSpritesheet(require('assets/spritesheets/s_whip')),'whip')
asm:add(asset:newSpritesheet(require('assets/spritesheets/s_title')),'title')
asm:add(asset:newSpritesheet(require('assets/spritesheets/s_gameover')),'gameover')
asm:add(asset:newSpritesheet(require('assets/spritesheets/s_lifebar')),'lifebar')
